apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dogecoin-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"   # Disable SSL redirect (just for testing purposes)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP" # Set backend protocol to HTTP (just for testing purposes)
spec:
  ingressClassName: nginx
  rules:
  - host: localhost # Change to your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dogecoin-forecasting
            port:
              number: 8501