apiVersion: v1
kind: PersistentVolume
metadata:
  name: dogecoin-logs-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/dogecoin-logs"